#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRada1.DTO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_Radar")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertST_BanDo(ST_BanDo instance);
    partial void UpdateST_BanDo(ST_BanDo instance);
    partial void DeleteST_BanDo(ST_BanDo instance);
    partial void InsertST_VungNguyHiem(ST_VungNguyHiem instance);
    partial void UpdateST_VungNguyHiem(ST_VungNguyHiem instance);
    partial void DeleteST_VungNguyHiem(ST_VungNguyHiem instance);
    partial void InsertST_Department(ST_Department instance);
    partial void UpdateST_Department(ST_Department instance);
    partial void DeleteST_Department(ST_Department instance);
    partial void InsertST_HoatDong(ST_HoatDong instance);
    partial void UpdateST_HoatDong(ST_HoatDong instance);
    partial void DeleteST_HoatDong(ST_HoatDong instance);
    partial void InsertST_Image(ST_Image instance);
    partial void UpdateST_Image(ST_Image instance);
    partial void DeleteST_Image(ST_Image instance);
    partial void InsertST_RaDa(ST_RaDa instance);
    partial void UpdateST_RaDa(ST_RaDa instance);
    partial void DeleteST_RaDa(ST_RaDa instance);
    partial void InsertST_target(ST_target instance);
    partial void UpdateST_target(ST_target instance);
    partial void DeleteST_target(ST_target instance);
    partial void InsertST_User(ST_User instance);
    partial void UpdateST_User(ST_User instance);
    partial void DeleteST_User(ST_User instance);
    partial void InsertST_VatThe(ST_VatThe instance);
    partial void UpdateST_VatThe(ST_VatThe instance);
    partial void DeleteST_VatThe(ST_VatThe instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::TestRada1.Properties.Settings.Default.DB_RadarConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ST_BanDo> ST_BanDos
		{
			get
			{
				return this.GetTable<ST_BanDo>();
			}
		}
		
		public System.Data.Linq.Table<ST_VungNguyHiem> ST_VungNguyHiems
		{
			get
			{
				return this.GetTable<ST_VungNguyHiem>();
			}
		}
		
		public System.Data.Linq.Table<ST_Department> ST_Departments
		{
			get
			{
				return this.GetTable<ST_Department>();
			}
		}
		
		public System.Data.Linq.Table<ST_HoatDong> ST_HoatDongs
		{
			get
			{
				return this.GetTable<ST_HoatDong>();
			}
		}
		
		public System.Data.Linq.Table<ST_Image> ST_Images
		{
			get
			{
				return this.GetTable<ST_Image>();
			}
		}
		
		public System.Data.Linq.Table<ST_RaDa> ST_RaDas
		{
			get
			{
				return this.GetTable<ST_RaDa>();
			}
		}
		
		public System.Data.Linq.Table<ST_target> ST_targets
		{
			get
			{
				return this.GetTable<ST_target>();
			}
		}
		
		public System.Data.Linq.Table<ST_User> ST_Users
		{
			get
			{
				return this.GetTable<ST_User>();
			}
		}
		
		public System.Data.Linq.Table<ST_VatThe> ST_VatThes
		{
			get
			{
				return this.GetTable<ST_VatThe>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ST_BanDo")]
	public partial class ST_BanDo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _bando_id;
		
		private string _bando_name;
		
		private double _bando_x;
		
		private double _bando_y;
		
		private System.Data.Linq.Binary _bando_image;
		
		private System.Nullable<bool> _bando_tinhTrang;
		
		private System.Nullable<long> _user_created;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbando_idChanging(long value);
    partial void Onbando_idChanged();
    partial void Onbando_nameChanging(string value);
    partial void Onbando_nameChanged();
    partial void Onbando_xChanging(double value);
    partial void Onbando_xChanged();
    partial void Onbando_yChanging(double value);
    partial void Onbando_yChanged();
    partial void Onbando_imageChanging(System.Data.Linq.Binary value);
    partial void Onbando_imageChanged();
    partial void Onbando_tinhTrangChanging(System.Nullable<bool> value);
    partial void Onbando_tinhTrangChanged();
    partial void Onuser_createdChanging(System.Nullable<long> value);
    partial void Onuser_createdChanged();
    #endregion
		
		public ST_BanDo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bando_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long bando_id
		{
			get
			{
				return this._bando_id;
			}
			set
			{
				if ((this._bando_id != value))
				{
					this.Onbando_idChanging(value);
					this.SendPropertyChanging();
					this._bando_id = value;
					this.SendPropertyChanged("bando_id");
					this.Onbando_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bando_name", DbType="NVarChar(200)")]
		public string bando_name
		{
			get
			{
				return this._bando_name;
			}
			set
			{
				if ((this._bando_name != value))
				{
					this.Onbando_nameChanging(value);
					this.SendPropertyChanging();
					this._bando_name = value;
					this.SendPropertyChanged("bando_name");
					this.Onbando_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bando_x", DbType="Float NOT NULL")]
		public double bando_x
		{
			get
			{
				return this._bando_x;
			}
			set
			{
				if ((this._bando_x != value))
				{
					this.Onbando_xChanging(value);
					this.SendPropertyChanging();
					this._bando_x = value;
					this.SendPropertyChanged("bando_x");
					this.Onbando_xChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bando_y", DbType="Float NOT NULL")]
		public double bando_y
		{
			get
			{
				return this._bando_y;
			}
			set
			{
				if ((this._bando_y != value))
				{
					this.Onbando_yChanging(value);
					this.SendPropertyChanging();
					this._bando_y = value;
					this.SendPropertyChanged("bando_y");
					this.Onbando_yChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bando_image", DbType="Image NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary bando_image
		{
			get
			{
				return this._bando_image;
			}
			set
			{
				if ((this._bando_image != value))
				{
					this.Onbando_imageChanging(value);
					this.SendPropertyChanging();
					this._bando_image = value;
					this.SendPropertyChanged("bando_image");
					this.Onbando_imageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bando_tinhTrang", DbType="Bit")]
		public System.Nullable<bool> bando_tinhTrang
		{
			get
			{
				return this._bando_tinhTrang;
			}
			set
			{
				if ((this._bando_tinhTrang != value))
				{
					this.Onbando_tinhTrangChanging(value);
					this.SendPropertyChanging();
					this._bando_tinhTrang = value;
					this.SendPropertyChanged("bando_tinhTrang");
					this.Onbando_tinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_created", DbType="BigInt")]
		public System.Nullable<long> user_created
		{
			get
			{
				return this._user_created;
			}
			set
			{
				if ((this._user_created != value))
				{
					this.Onuser_createdChanging(value);
					this.SendPropertyChanging();
					this._user_created = value;
					this.SendPropertyChanged("user_created");
					this.Onuser_createdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ST_VungNguyHiem")]
	public partial class ST_VungNguyHiem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _vungNguyHiem_id;
		
		private string _vungNguyHiem_loai;
		
		private System.Nullable<int> _vungNguyHiem_ban_kinh;
		
		private System.Nullable<int> _vungNguyHiem_1_X;
		
		private System.Nullable<int> _vungNguyHiem_1_Y;
		
		private System.Nullable<int> _vungNguyHiem_2_X;
		
		private System.Nullable<int> _vungNguyHiem_2_Y;
		
		private System.Nullable<int> _vungNguyHiem_3_X;
		
		private System.Nullable<int> _vungNguyHiem_3_Y;
		
		private System.Nullable<int> _vungNguyHiem_4_X;
		
		private System.Nullable<int> _vungNguyHiem_4_Y;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnvungNguyHiem_idChanging(long value);
    partial void OnvungNguyHiem_idChanged();
    partial void OnvungNguyHiem_loaiChanging(string value);
    partial void OnvungNguyHiem_loaiChanged();
    partial void OnvungNguyHiem_ban_kinhChanging(System.Nullable<int> value);
    partial void OnvungNguyHiem_ban_kinhChanged();
    partial void OnvungNguyHiem_1_XChanging(System.Nullable<int> value);
    partial void OnvungNguyHiem_1_XChanged();
    partial void OnvungNguyHiem_1_YChanging(System.Nullable<int> value);
    partial void OnvungNguyHiem_1_YChanged();
    partial void OnvungNguyHiem_2_XChanging(System.Nullable<int> value);
    partial void OnvungNguyHiem_2_XChanged();
    partial void OnvungNguyHiem_2_YChanging(System.Nullable<int> value);
    partial void OnvungNguyHiem_2_YChanged();
    partial void OnvungNguyHiem_3_XChanging(System.Nullable<int> value);
    partial void OnvungNguyHiem_3_XChanged();
    partial void OnvungNguyHiem_3_YChanging(System.Nullable<int> value);
    partial void OnvungNguyHiem_3_YChanged();
    partial void OnvungNguyHiem_4_XChanging(System.Nullable<int> value);
    partial void OnvungNguyHiem_4_XChanged();
    partial void OnvungNguyHiem_4_YChanging(System.Nullable<int> value);
    partial void OnvungNguyHiem_4_YChanged();
    #endregion
		
		public ST_VungNguyHiem()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vungNguyHiem_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long vungNguyHiem_id
		{
			get
			{
				return this._vungNguyHiem_id;
			}
			set
			{
				if ((this._vungNguyHiem_id != value))
				{
					this.OnvungNguyHiem_idChanging(value);
					this.SendPropertyChanging();
					this._vungNguyHiem_id = value;
					this.SendPropertyChanged("vungNguyHiem_id");
					this.OnvungNguyHiem_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vungNguyHiem_loai", DbType="NVarChar(50)")]
		public string vungNguyHiem_loai
		{
			get
			{
				return this._vungNguyHiem_loai;
			}
			set
			{
				if ((this._vungNguyHiem_loai != value))
				{
					this.OnvungNguyHiem_loaiChanging(value);
					this.SendPropertyChanging();
					this._vungNguyHiem_loai = value;
					this.SendPropertyChanged("vungNguyHiem_loai");
					this.OnvungNguyHiem_loaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vungNguyHiem_ban_kinh", DbType="Int")]
		public System.Nullable<int> vungNguyHiem_ban_kinh
		{
			get
			{
				return this._vungNguyHiem_ban_kinh;
			}
			set
			{
				if ((this._vungNguyHiem_ban_kinh != value))
				{
					this.OnvungNguyHiem_ban_kinhChanging(value);
					this.SendPropertyChanging();
					this._vungNguyHiem_ban_kinh = value;
					this.SendPropertyChanged("vungNguyHiem_ban_kinh");
					this.OnvungNguyHiem_ban_kinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vungNguyHiem_1_X", DbType="Int")]
		public System.Nullable<int> vungNguyHiem_1_X
		{
			get
			{
				return this._vungNguyHiem_1_X;
			}
			set
			{
				if ((this._vungNguyHiem_1_X != value))
				{
					this.OnvungNguyHiem_1_XChanging(value);
					this.SendPropertyChanging();
					this._vungNguyHiem_1_X = value;
					this.SendPropertyChanged("vungNguyHiem_1_X");
					this.OnvungNguyHiem_1_XChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vungNguyHiem_1_Y", DbType="Int")]
		public System.Nullable<int> vungNguyHiem_1_Y
		{
			get
			{
				return this._vungNguyHiem_1_Y;
			}
			set
			{
				if ((this._vungNguyHiem_1_Y != value))
				{
					this.OnvungNguyHiem_1_YChanging(value);
					this.SendPropertyChanging();
					this._vungNguyHiem_1_Y = value;
					this.SendPropertyChanged("vungNguyHiem_1_Y");
					this.OnvungNguyHiem_1_YChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vungNguyHiem_2_X", DbType="Int")]
		public System.Nullable<int> vungNguyHiem_2_X
		{
			get
			{
				return this._vungNguyHiem_2_X;
			}
			set
			{
				if ((this._vungNguyHiem_2_X != value))
				{
					this.OnvungNguyHiem_2_XChanging(value);
					this.SendPropertyChanging();
					this._vungNguyHiem_2_X = value;
					this.SendPropertyChanged("vungNguyHiem_2_X");
					this.OnvungNguyHiem_2_XChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vungNguyHiem_2_Y", DbType="Int")]
		public System.Nullable<int> vungNguyHiem_2_Y
		{
			get
			{
				return this._vungNguyHiem_2_Y;
			}
			set
			{
				if ((this._vungNguyHiem_2_Y != value))
				{
					this.OnvungNguyHiem_2_YChanging(value);
					this.SendPropertyChanging();
					this._vungNguyHiem_2_Y = value;
					this.SendPropertyChanged("vungNguyHiem_2_Y");
					this.OnvungNguyHiem_2_YChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vungNguyHiem_3_X", DbType="Int")]
		public System.Nullable<int> vungNguyHiem_3_X
		{
			get
			{
				return this._vungNguyHiem_3_X;
			}
			set
			{
				if ((this._vungNguyHiem_3_X != value))
				{
					this.OnvungNguyHiem_3_XChanging(value);
					this.SendPropertyChanging();
					this._vungNguyHiem_3_X = value;
					this.SendPropertyChanged("vungNguyHiem_3_X");
					this.OnvungNguyHiem_3_XChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vungNguyHiem_3_Y", DbType="Int")]
		public System.Nullable<int> vungNguyHiem_3_Y
		{
			get
			{
				return this._vungNguyHiem_3_Y;
			}
			set
			{
				if ((this._vungNguyHiem_3_Y != value))
				{
					this.OnvungNguyHiem_3_YChanging(value);
					this.SendPropertyChanging();
					this._vungNguyHiem_3_Y = value;
					this.SendPropertyChanged("vungNguyHiem_3_Y");
					this.OnvungNguyHiem_3_YChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vungNguyHiem_4_X", DbType="Int")]
		public System.Nullable<int> vungNguyHiem_4_X
		{
			get
			{
				return this._vungNguyHiem_4_X;
			}
			set
			{
				if ((this._vungNguyHiem_4_X != value))
				{
					this.OnvungNguyHiem_4_XChanging(value);
					this.SendPropertyChanging();
					this._vungNguyHiem_4_X = value;
					this.SendPropertyChanged("vungNguyHiem_4_X");
					this.OnvungNguyHiem_4_XChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vungNguyHiem_4_Y", DbType="Int")]
		public System.Nullable<int> vungNguyHiem_4_Y
		{
			get
			{
				return this._vungNguyHiem_4_Y;
			}
			set
			{
				if ((this._vungNguyHiem_4_Y != value))
				{
					this.OnvungNguyHiem_4_YChanging(value);
					this.SendPropertyChanging();
					this._vungNguyHiem_4_Y = value;
					this.SendPropertyChanged("vungNguyHiem_4_Y");
					this.OnvungNguyHiem_4_YChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ST_Departments")]
	public partial class ST_Department : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _department_id;
		
		private string _department_name;
		
		private System.Nullable<long> _user_created;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondepartment_idChanging(long value);
    partial void Ondepartment_idChanged();
    partial void Ondepartment_nameChanging(string value);
    partial void Ondepartment_nameChanged();
    partial void Onuser_createdChanging(System.Nullable<long> value);
    partial void Onuser_createdChanged();
    #endregion
		
		public ST_Department()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long department_id
		{
			get
			{
				return this._department_id;
			}
			set
			{
				if ((this._department_id != value))
				{
					this.Ondepartment_idChanging(value);
					this.SendPropertyChanging();
					this._department_id = value;
					this.SendPropertyChanged("department_id");
					this.Ondepartment_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department_name", DbType="NVarChar(200)")]
		public string department_name
		{
			get
			{
				return this._department_name;
			}
			set
			{
				if ((this._department_name != value))
				{
					this.Ondepartment_nameChanging(value);
					this.SendPropertyChanging();
					this._department_name = value;
					this.SendPropertyChanged("department_name");
					this.Ondepartment_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_created", DbType="BigInt")]
		public System.Nullable<long> user_created
		{
			get
			{
				return this._user_created;
			}
			set
			{
				if ((this._user_created != value))
				{
					this.Onuser_createdChanging(value);
					this.SendPropertyChanging();
					this._user_created = value;
					this.SendPropertyChanged("user_created");
					this.Onuser_createdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ST_HoatDong")]
	public partial class ST_HoatDong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _HoatDong_id;
		
		private System.Nullable<int> _vatThe_id;
		
		private System.Nullable<int> _HoatDong_xBatDau;
		
		private System.Nullable<int> _HoatDong_yBatDau;
		
		private System.Nullable<int> _HoatDong_xKetThuc;
		
		private System.Nullable<int> _HoatDong_yKetThuc;
		
		private System.Nullable<int> _HoatDong_soBuocNhay;
		
		private System.Nullable<System.DateTime> _HoatDong_thoiGianBatDauChay;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHoatDong_idChanging(int value);
    partial void OnHoatDong_idChanged();
    partial void OnvatThe_idChanging(System.Nullable<int> value);
    partial void OnvatThe_idChanged();
    partial void OnHoatDong_xBatDauChanging(System.Nullable<int> value);
    partial void OnHoatDong_xBatDauChanged();
    partial void OnHoatDong_yBatDauChanging(System.Nullable<int> value);
    partial void OnHoatDong_yBatDauChanged();
    partial void OnHoatDong_xKetThucChanging(System.Nullable<int> value);
    partial void OnHoatDong_xKetThucChanged();
    partial void OnHoatDong_yKetThucChanging(System.Nullable<int> value);
    partial void OnHoatDong_yKetThucChanged();
    partial void OnHoatDong_soBuocNhayChanging(System.Nullable<int> value);
    partial void OnHoatDong_soBuocNhayChanged();
    partial void OnHoatDong_thoiGianBatDauChayChanging(System.Nullable<System.DateTime> value);
    partial void OnHoatDong_thoiGianBatDauChayChanged();
    #endregion
		
		public ST_HoatDong()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoatDong_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int HoatDong_id
		{
			get
			{
				return this._HoatDong_id;
			}
			set
			{
				if ((this._HoatDong_id != value))
				{
					this.OnHoatDong_idChanging(value);
					this.SendPropertyChanging();
					this._HoatDong_id = value;
					this.SendPropertyChanged("HoatDong_id");
					this.OnHoatDong_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vatThe_id", DbType="Int")]
		public System.Nullable<int> vatThe_id
		{
			get
			{
				return this._vatThe_id;
			}
			set
			{
				if ((this._vatThe_id != value))
				{
					this.OnvatThe_idChanging(value);
					this.SendPropertyChanging();
					this._vatThe_id = value;
					this.SendPropertyChanged("vatThe_id");
					this.OnvatThe_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoatDong_xBatDau", DbType="Int")]
		public System.Nullable<int> HoatDong_xBatDau
		{
			get
			{
				return this._HoatDong_xBatDau;
			}
			set
			{
				if ((this._HoatDong_xBatDau != value))
				{
					this.OnHoatDong_xBatDauChanging(value);
					this.SendPropertyChanging();
					this._HoatDong_xBatDau = value;
					this.SendPropertyChanged("HoatDong_xBatDau");
					this.OnHoatDong_xBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoatDong_yBatDau", DbType="Int")]
		public System.Nullable<int> HoatDong_yBatDau
		{
			get
			{
				return this._HoatDong_yBatDau;
			}
			set
			{
				if ((this._HoatDong_yBatDau != value))
				{
					this.OnHoatDong_yBatDauChanging(value);
					this.SendPropertyChanging();
					this._HoatDong_yBatDau = value;
					this.SendPropertyChanged("HoatDong_yBatDau");
					this.OnHoatDong_yBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoatDong_xKetThuc", DbType="Int")]
		public System.Nullable<int> HoatDong_xKetThuc
		{
			get
			{
				return this._HoatDong_xKetThuc;
			}
			set
			{
				if ((this._HoatDong_xKetThuc != value))
				{
					this.OnHoatDong_xKetThucChanging(value);
					this.SendPropertyChanging();
					this._HoatDong_xKetThuc = value;
					this.SendPropertyChanged("HoatDong_xKetThuc");
					this.OnHoatDong_xKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoatDong_yKetThuc", DbType="Int")]
		public System.Nullable<int> HoatDong_yKetThuc
		{
			get
			{
				return this._HoatDong_yKetThuc;
			}
			set
			{
				if ((this._HoatDong_yKetThuc != value))
				{
					this.OnHoatDong_yKetThucChanging(value);
					this.SendPropertyChanging();
					this._HoatDong_yKetThuc = value;
					this.SendPropertyChanged("HoatDong_yKetThuc");
					this.OnHoatDong_yKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoatDong_soBuocNhay", DbType="Int")]
		public System.Nullable<int> HoatDong_soBuocNhay
		{
			get
			{
				return this._HoatDong_soBuocNhay;
			}
			set
			{
				if ((this._HoatDong_soBuocNhay != value))
				{
					this.OnHoatDong_soBuocNhayChanging(value);
					this.SendPropertyChanging();
					this._HoatDong_soBuocNhay = value;
					this.SendPropertyChanged("HoatDong_soBuocNhay");
					this.OnHoatDong_soBuocNhayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoatDong_thoiGianBatDauChay", DbType="DateTime")]
		public System.Nullable<System.DateTime> HoatDong_thoiGianBatDauChay
		{
			get
			{
				return this._HoatDong_thoiGianBatDauChay;
			}
			set
			{
				if ((this._HoatDong_thoiGianBatDauChay != value))
				{
					this.OnHoatDong_thoiGianBatDauChayChanging(value);
					this.SendPropertyChanging();
					this._HoatDong_thoiGianBatDauChay = value;
					this.SendPropertyChanged("HoatDong_thoiGianBatDauChay");
					this.OnHoatDong_thoiGianBatDauChayChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ST_Images")]
	public partial class ST_Image : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _image_id;
		
		private string _image_name;
		
		private System.Data.Linq.Binary _image_img;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onimage_idChanging(int value);
    partial void Onimage_idChanged();
    partial void Onimage_nameChanging(string value);
    partial void Onimage_nameChanged();
    partial void Onimage_imgChanging(System.Data.Linq.Binary value);
    partial void Onimage_imgChanged();
    #endregion
		
		public ST_Image()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int image_id
		{
			get
			{
				return this._image_id;
			}
			set
			{
				if ((this._image_id != value))
				{
					this.Onimage_idChanging(value);
					this.SendPropertyChanging();
					this._image_id = value;
					this.SendPropertyChanged("image_id");
					this.Onimage_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image_name", DbType="NVarChar(50)")]
		public string image_name
		{
			get
			{
				return this._image_name;
			}
			set
			{
				if ((this._image_name != value))
				{
					this.Onimage_nameChanging(value);
					this.SendPropertyChanging();
					this._image_name = value;
					this.SendPropertyChanged("image_name");
					this.Onimage_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image_img", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary image_img
		{
			get
			{
				return this._image_img;
			}
			set
			{
				if ((this._image_img != value))
				{
					this.Onimage_imgChanging(value);
					this.SendPropertyChanging();
					this._image_img = value;
					this.SendPropertyChanged("image_img");
					this.Onimage_imgChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ST_RaDa")]
	public partial class ST_RaDa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _rada_id;
		
		private string _rada_name;
		
		private double _rada_x;
		
		private double _rada_y;
		
		private System.Nullable<long> _bando_id;
		
		private System.Nullable<long> _user_created;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onrada_idChanging(long value);
    partial void Onrada_idChanged();
    partial void Onrada_nameChanging(string value);
    partial void Onrada_nameChanged();
    partial void Onrada_xChanging(double value);
    partial void Onrada_xChanged();
    partial void Onrada_yChanging(double value);
    partial void Onrada_yChanged();
    partial void Onbando_idChanging(System.Nullable<long> value);
    partial void Onbando_idChanged();
    partial void Onuser_createdChanging(System.Nullable<long> value);
    partial void Onuser_createdChanged();
    #endregion
		
		public ST_RaDa()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rada_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long rada_id
		{
			get
			{
				return this._rada_id;
			}
			set
			{
				if ((this._rada_id != value))
				{
					this.Onrada_idChanging(value);
					this.SendPropertyChanging();
					this._rada_id = value;
					this.SendPropertyChanged("rada_id");
					this.Onrada_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rada_name", DbType="NVarChar(200)")]
		public string rada_name
		{
			get
			{
				return this._rada_name;
			}
			set
			{
				if ((this._rada_name != value))
				{
					this.Onrada_nameChanging(value);
					this.SendPropertyChanging();
					this._rada_name = value;
					this.SendPropertyChanged("rada_name");
					this.Onrada_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rada_x", DbType="Float NOT NULL")]
		public double rada_x
		{
			get
			{
				return this._rada_x;
			}
			set
			{
				if ((this._rada_x != value))
				{
					this.Onrada_xChanging(value);
					this.SendPropertyChanging();
					this._rada_x = value;
					this.SendPropertyChanged("rada_x");
					this.Onrada_xChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rada_y", DbType="Float NOT NULL")]
		public double rada_y
		{
			get
			{
				return this._rada_y;
			}
			set
			{
				if ((this._rada_y != value))
				{
					this.Onrada_yChanging(value);
					this.SendPropertyChanging();
					this._rada_y = value;
					this.SendPropertyChanged("rada_y");
					this.Onrada_yChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bando_id", DbType="BigInt")]
		public System.Nullable<long> bando_id
		{
			get
			{
				return this._bando_id;
			}
			set
			{
				if ((this._bando_id != value))
				{
					this.Onbando_idChanging(value);
					this.SendPropertyChanging();
					this._bando_id = value;
					this.SendPropertyChanged("bando_id");
					this.Onbando_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_created", DbType="BigInt")]
		public System.Nullable<long> user_created
		{
			get
			{
				return this._user_created;
			}
			set
			{
				if ((this._user_created != value))
				{
					this.Onuser_createdChanging(value);
					this.SendPropertyChanging();
					this._user_created = value;
					this.SendPropertyChanged("user_created");
					this.Onuser_createdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ST_target")]
	public partial class ST_target : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _target_id;
		
		private string _target_name;
		
		private string _target_true_heading;
		
		private string _target_true_heading_unit;
		
		private string _target_course_over_ground;
		
		private string _target_course_over_ground_unit;
		
		private string _target_speed_over_ground;
		
		private string _target_speed_over_ground_unit;
		
		private string _target_rate_of_turn;
		
		private string _target_rate_of_turn_unit;
		
		private string _target_call_sign;
		
		private string _target_MMSI;
		
		private string _target_navigation_status;
		
		private string _target_type_of_ship;
		
		private string _target_draught;
		
		private string _target_draught_unit;
		
		private string _target_lenght;
		
		private string _target_lenght_unit;
		
		private string _target_width;
		
		private string _target_width_unit;
		
		private string _target_Destination;
		
		private string _target_speed;
		
		private string _target_speed_unit;
		
		private string _target_height;
		
		private string _target_height_unit;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontarget_idChanging(int value);
    partial void Ontarget_idChanged();
    partial void Ontarget_nameChanging(string value);
    partial void Ontarget_nameChanged();
    partial void Ontarget_true_headingChanging(string value);
    partial void Ontarget_true_headingChanged();
    partial void Ontarget_true_heading_unitChanging(string value);
    partial void Ontarget_true_heading_unitChanged();
    partial void Ontarget_course_over_groundChanging(string value);
    partial void Ontarget_course_over_groundChanged();
    partial void Ontarget_course_over_ground_unitChanging(string value);
    partial void Ontarget_course_over_ground_unitChanged();
    partial void Ontarget_speed_over_groundChanging(string value);
    partial void Ontarget_speed_over_groundChanged();
    partial void Ontarget_speed_over_ground_unitChanging(string value);
    partial void Ontarget_speed_over_ground_unitChanged();
    partial void Ontarget_rate_of_turnChanging(string value);
    partial void Ontarget_rate_of_turnChanged();
    partial void Ontarget_rate_of_turn_unitChanging(string value);
    partial void Ontarget_rate_of_turn_unitChanged();
    partial void Ontarget_call_signChanging(string value);
    partial void Ontarget_call_signChanged();
    partial void Ontarget_MMSIChanging(string value);
    partial void Ontarget_MMSIChanged();
    partial void Ontarget_navigation_statusChanging(string value);
    partial void Ontarget_navigation_statusChanged();
    partial void Ontarget_type_of_shipChanging(string value);
    partial void Ontarget_type_of_shipChanged();
    partial void Ontarget_draughtChanging(string value);
    partial void Ontarget_draughtChanged();
    partial void Ontarget_draught_unitChanging(string value);
    partial void Ontarget_draught_unitChanged();
    partial void Ontarget_lenghtChanging(string value);
    partial void Ontarget_lenghtChanged();
    partial void Ontarget_lenght_unitChanging(string value);
    partial void Ontarget_lenght_unitChanged();
    partial void Ontarget_widthChanging(string value);
    partial void Ontarget_widthChanged();
    partial void Ontarget_width_unitChanging(string value);
    partial void Ontarget_width_unitChanged();
    partial void Ontarget_DestinationChanging(string value);
    partial void Ontarget_DestinationChanged();
    partial void Ontarget_speedChanging(string value);
    partial void Ontarget_speedChanged();
    partial void Ontarget_speed_unitChanging(string value);
    partial void Ontarget_speed_unitChanged();
    partial void Ontarget_heightChanging(string value);
    partial void Ontarget_heightChanged();
    partial void Ontarget_height_unitChanging(string value);
    partial void Ontarget_height_unitChanged();
    #endregion
		
		public ST_target()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int target_id
		{
			get
			{
				return this._target_id;
			}
			set
			{
				if ((this._target_id != value))
				{
					this.Ontarget_idChanging(value);
					this.SendPropertyChanging();
					this._target_id = value;
					this.SendPropertyChanged("target_id");
					this.Ontarget_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target_name", DbType="NVarChar(50)")]
		public string target_name
		{
			get
			{
				return this._target_name;
			}
			set
			{
				if ((this._target_name != value))
				{
					this.Ontarget_nameChanging(value);
					this.SendPropertyChanging();
					this._target_name = value;
					this.SendPropertyChanged("target_name");
					this.Ontarget_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target_true_heading", DbType="NVarChar(50)")]
		public string target_true_heading
		{
			get
			{
				return this._target_true_heading;
			}
			set
			{
				if ((this._target_true_heading != value))
				{
					this.Ontarget_true_headingChanging(value);
					this.SendPropertyChanging();
					this._target_true_heading = value;
					this.SendPropertyChanged("target_true_heading");
					this.Ontarget_true_headingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target_true_heading_unit", DbType="NVarChar(50)")]
		public string target_true_heading_unit
		{
			get
			{
				return this._target_true_heading_unit;
			}
			set
			{
				if ((this._target_true_heading_unit != value))
				{
					this.Ontarget_true_heading_unitChanging(value);
					this.SendPropertyChanging();
					this._target_true_heading_unit = value;
					this.SendPropertyChanged("target_true_heading_unit");
					this.Ontarget_true_heading_unitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target_course_over_ground", DbType="NVarChar(50)")]
		public string target_course_over_ground
		{
			get
			{
				return this._target_course_over_ground;
			}
			set
			{
				if ((this._target_course_over_ground != value))
				{
					this.Ontarget_course_over_groundChanging(value);
					this.SendPropertyChanging();
					this._target_course_over_ground = value;
					this.SendPropertyChanged("target_course_over_ground");
					this.Ontarget_course_over_groundChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target_course_over_ground_unit", DbType="NVarChar(50)")]
		public string target_course_over_ground_unit
		{
			get
			{
				return this._target_course_over_ground_unit;
			}
			set
			{
				if ((this._target_course_over_ground_unit != value))
				{
					this.Ontarget_course_over_ground_unitChanging(value);
					this.SendPropertyChanging();
					this._target_course_over_ground_unit = value;
					this.SendPropertyChanged("target_course_over_ground_unit");
					this.Ontarget_course_over_ground_unitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target_speed_over_ground", DbType="NVarChar(50)")]
		public string target_speed_over_ground
		{
			get
			{
				return this._target_speed_over_ground;
			}
			set
			{
				if ((this._target_speed_over_ground != value))
				{
					this.Ontarget_speed_over_groundChanging(value);
					this.SendPropertyChanging();
					this._target_speed_over_ground = value;
					this.SendPropertyChanged("target_speed_over_ground");
					this.Ontarget_speed_over_groundChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target_speed_over_ground_unit", DbType="NVarChar(50)")]
		public string target_speed_over_ground_unit
		{
			get
			{
				return this._target_speed_over_ground_unit;
			}
			set
			{
				if ((this._target_speed_over_ground_unit != value))
				{
					this.Ontarget_speed_over_ground_unitChanging(value);
					this.SendPropertyChanging();
					this._target_speed_over_ground_unit = value;
					this.SendPropertyChanged("target_speed_over_ground_unit");
					this.Ontarget_speed_over_ground_unitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target_rate_of_turn", DbType="NVarChar(50)")]
		public string target_rate_of_turn
		{
			get
			{
				return this._target_rate_of_turn;
			}
			set
			{
				if ((this._target_rate_of_turn != value))
				{
					this.Ontarget_rate_of_turnChanging(value);
					this.SendPropertyChanging();
					this._target_rate_of_turn = value;
					this.SendPropertyChanged("target_rate_of_turn");
					this.Ontarget_rate_of_turnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target_rate_of_turn_unit", DbType="NVarChar(50)")]
		public string target_rate_of_turn_unit
		{
			get
			{
				return this._target_rate_of_turn_unit;
			}
			set
			{
				if ((this._target_rate_of_turn_unit != value))
				{
					this.Ontarget_rate_of_turn_unitChanging(value);
					this.SendPropertyChanging();
					this._target_rate_of_turn_unit = value;
					this.SendPropertyChanged("target_rate_of_turn_unit");
					this.Ontarget_rate_of_turn_unitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target_call_sign", DbType="NVarChar(50)")]
		public string target_call_sign
		{
			get
			{
				return this._target_call_sign;
			}
			set
			{
				if ((this._target_call_sign != value))
				{
					this.Ontarget_call_signChanging(value);
					this.SendPropertyChanging();
					this._target_call_sign = value;
					this.SendPropertyChanged("target_call_sign");
					this.Ontarget_call_signChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target_MMSI", DbType="NVarChar(50)")]
		public string target_MMSI
		{
			get
			{
				return this._target_MMSI;
			}
			set
			{
				if ((this._target_MMSI != value))
				{
					this.Ontarget_MMSIChanging(value);
					this.SendPropertyChanging();
					this._target_MMSI = value;
					this.SendPropertyChanged("target_MMSI");
					this.Ontarget_MMSIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target_navigation_status", DbType="NVarChar(50)")]
		public string target_navigation_status
		{
			get
			{
				return this._target_navigation_status;
			}
			set
			{
				if ((this._target_navigation_status != value))
				{
					this.Ontarget_navigation_statusChanging(value);
					this.SendPropertyChanging();
					this._target_navigation_status = value;
					this.SendPropertyChanged("target_navigation_status");
					this.Ontarget_navigation_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target_type_of_ship", DbType="NVarChar(50)")]
		public string target_type_of_ship
		{
			get
			{
				return this._target_type_of_ship;
			}
			set
			{
				if ((this._target_type_of_ship != value))
				{
					this.Ontarget_type_of_shipChanging(value);
					this.SendPropertyChanging();
					this._target_type_of_ship = value;
					this.SendPropertyChanged("target_type_of_ship");
					this.Ontarget_type_of_shipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target_draught", DbType="NVarChar(50)")]
		public string target_draught
		{
			get
			{
				return this._target_draught;
			}
			set
			{
				if ((this._target_draught != value))
				{
					this.Ontarget_draughtChanging(value);
					this.SendPropertyChanging();
					this._target_draught = value;
					this.SendPropertyChanged("target_draught");
					this.Ontarget_draughtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target_draught_unit", DbType="NVarChar(50)")]
		public string target_draught_unit
		{
			get
			{
				return this._target_draught_unit;
			}
			set
			{
				if ((this._target_draught_unit != value))
				{
					this.Ontarget_draught_unitChanging(value);
					this.SendPropertyChanging();
					this._target_draught_unit = value;
					this.SendPropertyChanged("target_draught_unit");
					this.Ontarget_draught_unitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target_lenght", DbType="NVarChar(50)")]
		public string target_lenght
		{
			get
			{
				return this._target_lenght;
			}
			set
			{
				if ((this._target_lenght != value))
				{
					this.Ontarget_lenghtChanging(value);
					this.SendPropertyChanging();
					this._target_lenght = value;
					this.SendPropertyChanged("target_lenght");
					this.Ontarget_lenghtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target_lenght_unit", DbType="NVarChar(50)")]
		public string target_lenght_unit
		{
			get
			{
				return this._target_lenght_unit;
			}
			set
			{
				if ((this._target_lenght_unit != value))
				{
					this.Ontarget_lenght_unitChanging(value);
					this.SendPropertyChanging();
					this._target_lenght_unit = value;
					this.SendPropertyChanged("target_lenght_unit");
					this.Ontarget_lenght_unitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target_width", DbType="NVarChar(50)")]
		public string target_width
		{
			get
			{
				return this._target_width;
			}
			set
			{
				if ((this._target_width != value))
				{
					this.Ontarget_widthChanging(value);
					this.SendPropertyChanging();
					this._target_width = value;
					this.SendPropertyChanged("target_width");
					this.Ontarget_widthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target_width_unit", DbType="NVarChar(50)")]
		public string target_width_unit
		{
			get
			{
				return this._target_width_unit;
			}
			set
			{
				if ((this._target_width_unit != value))
				{
					this.Ontarget_width_unitChanging(value);
					this.SendPropertyChanging();
					this._target_width_unit = value;
					this.SendPropertyChanged("target_width_unit");
					this.Ontarget_width_unitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target_Destination", DbType="NVarChar(50)")]
		public string target_Destination
		{
			get
			{
				return this._target_Destination;
			}
			set
			{
				if ((this._target_Destination != value))
				{
					this.Ontarget_DestinationChanging(value);
					this.SendPropertyChanging();
					this._target_Destination = value;
					this.SendPropertyChanged("target_Destination");
					this.Ontarget_DestinationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target_speed", DbType="NVarChar(50)")]
		public string target_speed
		{
			get
			{
				return this._target_speed;
			}
			set
			{
				if ((this._target_speed != value))
				{
					this.Ontarget_speedChanging(value);
					this.SendPropertyChanging();
					this._target_speed = value;
					this.SendPropertyChanged("target_speed");
					this.Ontarget_speedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target_speed_unit", DbType="NVarChar(50)")]
		public string target_speed_unit
		{
			get
			{
				return this._target_speed_unit;
			}
			set
			{
				if ((this._target_speed_unit != value))
				{
					this.Ontarget_speed_unitChanging(value);
					this.SendPropertyChanging();
					this._target_speed_unit = value;
					this.SendPropertyChanged("target_speed_unit");
					this.Ontarget_speed_unitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target_height", DbType="NVarChar(50)")]
		public string target_height
		{
			get
			{
				return this._target_height;
			}
			set
			{
				if ((this._target_height != value))
				{
					this.Ontarget_heightChanging(value);
					this.SendPropertyChanging();
					this._target_height = value;
					this.SendPropertyChanged("target_height");
					this.Ontarget_heightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target_height_unit", DbType="NVarChar(50)")]
		public string target_height_unit
		{
			get
			{
				return this._target_height_unit;
			}
			set
			{
				if ((this._target_height_unit != value))
				{
					this.Ontarget_height_unitChanging(value);
					this.SendPropertyChanging();
					this._target_height_unit = value;
					this.SendPropertyChanged("target_height_unit");
					this.Ontarget_height_unitChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ST_Users")]
	public partial class ST_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _user_id;
		
		private string _user_name;
		
		private string _user_username;
		
		private string _user_password;
		
		private string _user_address;
		
		private string _user_email;
		
		private string _user_phone;
		
		private System.Nullable<System.DateTime> _user_date_of_birth;
		
		private System.Nullable<bool> _user_gender;
		
		private System.Data.Linq.Binary _user_image;
		
		private System.Nullable<long> _role_id;
		
		private System.Nullable<long> _department_id;
		
		private System.Nullable<bool> _user_status;
		
		private System.Nullable<System.DateTime> _user_created_date;
		
		private System.Nullable<long> _user_created;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(long value);
    partial void Onuser_idChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void Onuser_usernameChanging(string value);
    partial void Onuser_usernameChanged();
    partial void Onuser_passwordChanging(string value);
    partial void Onuser_passwordChanged();
    partial void Onuser_addressChanging(string value);
    partial void Onuser_addressChanged();
    partial void Onuser_emailChanging(string value);
    partial void Onuser_emailChanged();
    partial void Onuser_phoneChanging(string value);
    partial void Onuser_phoneChanged();
    partial void Onuser_date_of_birthChanging(System.Nullable<System.DateTime> value);
    partial void Onuser_date_of_birthChanged();
    partial void Onuser_genderChanging(System.Nullable<bool> value);
    partial void Onuser_genderChanged();
    partial void Onuser_imageChanging(System.Data.Linq.Binary value);
    partial void Onuser_imageChanged();
    partial void Onrole_idChanging(System.Nullable<long> value);
    partial void Onrole_idChanged();
    partial void Ondepartment_idChanging(System.Nullable<long> value);
    partial void Ondepartment_idChanged();
    partial void Onuser_statusChanging(System.Nullable<bool> value);
    partial void Onuser_statusChanged();
    partial void Onuser_created_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onuser_created_dateChanged();
    partial void Onuser_createdChanging(System.Nullable<long> value);
    partial void Onuser_createdChanged();
    #endregion
		
		public ST_User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="NVarChar(200)")]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_username", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string user_username
		{
			get
			{
				return this._user_username;
			}
			set
			{
				if ((this._user_username != value))
				{
					this.Onuser_usernameChanging(value);
					this.SendPropertyChanging();
					this._user_username = value;
					this.SendPropertyChanged("user_username");
					this.Onuser_usernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_password", DbType="VarChar(255)")]
		public string user_password
		{
			get
			{
				return this._user_password;
			}
			set
			{
				if ((this._user_password != value))
				{
					this.Onuser_passwordChanging(value);
					this.SendPropertyChanging();
					this._user_password = value;
					this.SendPropertyChanged("user_password");
					this.Onuser_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_address", DbType="NVarChar(255)")]
		public string user_address
		{
			get
			{
				return this._user_address;
			}
			set
			{
				if ((this._user_address != value))
				{
					this.Onuser_addressChanging(value);
					this.SendPropertyChanging();
					this._user_address = value;
					this.SendPropertyChanged("user_address");
					this.Onuser_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_email", DbType="VarChar(50)")]
		public string user_email
		{
			get
			{
				return this._user_email;
			}
			set
			{
				if ((this._user_email != value))
				{
					this.Onuser_emailChanging(value);
					this.SendPropertyChanging();
					this._user_email = value;
					this.SendPropertyChanged("user_email");
					this.Onuser_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_phone", DbType="NVarChar(50)")]
		public string user_phone
		{
			get
			{
				return this._user_phone;
			}
			set
			{
				if ((this._user_phone != value))
				{
					this.Onuser_phoneChanging(value);
					this.SendPropertyChanging();
					this._user_phone = value;
					this.SendPropertyChanged("user_phone");
					this.Onuser_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_date_of_birth", DbType="DateTime")]
		public System.Nullable<System.DateTime> user_date_of_birth
		{
			get
			{
				return this._user_date_of_birth;
			}
			set
			{
				if ((this._user_date_of_birth != value))
				{
					this.Onuser_date_of_birthChanging(value);
					this.SendPropertyChanging();
					this._user_date_of_birth = value;
					this.SendPropertyChanged("user_date_of_birth");
					this.Onuser_date_of_birthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_gender", DbType="Bit")]
		public System.Nullable<bool> user_gender
		{
			get
			{
				return this._user_gender;
			}
			set
			{
				if ((this._user_gender != value))
				{
					this.Onuser_genderChanging(value);
					this.SendPropertyChanging();
					this._user_gender = value;
					this.SendPropertyChanged("user_gender");
					this.Onuser_genderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_image", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary user_image
		{
			get
			{
				return this._user_image;
			}
			set
			{
				if ((this._user_image != value))
				{
					this.Onuser_imageChanging(value);
					this.SendPropertyChanging();
					this._user_image = value;
					this.SendPropertyChanged("user_image");
					this.Onuser_imageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role_id", DbType="BigInt")]
		public System.Nullable<long> role_id
		{
			get
			{
				return this._role_id;
			}
			set
			{
				if ((this._role_id != value))
				{
					this.Onrole_idChanging(value);
					this.SendPropertyChanging();
					this._role_id = value;
					this.SendPropertyChanged("role_id");
					this.Onrole_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department_id", DbType="BigInt")]
		public System.Nullable<long> department_id
		{
			get
			{
				return this._department_id;
			}
			set
			{
				if ((this._department_id != value))
				{
					this.Ondepartment_idChanging(value);
					this.SendPropertyChanging();
					this._department_id = value;
					this.SendPropertyChanged("department_id");
					this.Ondepartment_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_status", DbType="Bit")]
		public System.Nullable<bool> user_status
		{
			get
			{
				return this._user_status;
			}
			set
			{
				if ((this._user_status != value))
				{
					this.Onuser_statusChanging(value);
					this.SendPropertyChanging();
					this._user_status = value;
					this.SendPropertyChanged("user_status");
					this.Onuser_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_created_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> user_created_date
		{
			get
			{
				return this._user_created_date;
			}
			set
			{
				if ((this._user_created_date != value))
				{
					this.Onuser_created_dateChanging(value);
					this.SendPropertyChanging();
					this._user_created_date = value;
					this.SendPropertyChanged("user_created_date");
					this.Onuser_created_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_created", DbType="BigInt")]
		public System.Nullable<long> user_created
		{
			get
			{
				return this._user_created;
			}
			set
			{
				if ((this._user_created != value))
				{
					this.Onuser_createdChanging(value);
					this.SendPropertyChanging();
					this._user_created = value;
					this.SendPropertyChanged("user_created");
					this.Onuser_createdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ST_VatThe")]
	public partial class ST_VatThe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _vatThe_id;
		
		private string _vatThe_name;
		
		private System.Nullable<int> _image_id;
		
		private string _vatThe_mau;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnvatThe_idChanging(int value);
    partial void OnvatThe_idChanged();
    partial void OnvatThe_nameChanging(string value);
    partial void OnvatThe_nameChanged();
    partial void Onimage_idChanging(System.Nullable<int> value);
    partial void Onimage_idChanged();
    partial void OnvatThe_mauChanging(string value);
    partial void OnvatThe_mauChanged();
    #endregion
		
		public ST_VatThe()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vatThe_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int vatThe_id
		{
			get
			{
				return this._vatThe_id;
			}
			set
			{
				if ((this._vatThe_id != value))
				{
					this.OnvatThe_idChanging(value);
					this.SendPropertyChanging();
					this._vatThe_id = value;
					this.SendPropertyChanged("vatThe_id");
					this.OnvatThe_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vatThe_name", DbType="NVarChar(255)")]
		public string vatThe_name
		{
			get
			{
				return this._vatThe_name;
			}
			set
			{
				if ((this._vatThe_name != value))
				{
					this.OnvatThe_nameChanging(value);
					this.SendPropertyChanging();
					this._vatThe_name = value;
					this.SendPropertyChanged("vatThe_name");
					this.OnvatThe_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image_id", DbType="Int")]
		public System.Nullable<int> image_id
		{
			get
			{
				return this._image_id;
			}
			set
			{
				if ((this._image_id != value))
				{
					this.Onimage_idChanging(value);
					this.SendPropertyChanging();
					this._image_id = value;
					this.SendPropertyChanged("image_id");
					this.Onimage_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vatThe_mau", DbType="VarChar(20)")]
		public string vatThe_mau
		{
			get
			{
				return this._vatThe_mau;
			}
			set
			{
				if ((this._vatThe_mau != value))
				{
					this.OnvatThe_mauChanging(value);
					this.SendPropertyChanging();
					this._vatThe_mau = value;
					this.SendPropertyChanged("vatThe_mau");
					this.OnvatThe_mauChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
