#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRada1.DTO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_Radar")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertST_Department(ST_Department instance);
    partial void UpdateST_Department(ST_Department instance);
    partial void DeleteST_Department(ST_Department instance);
    partial void InsertST_VatThe(ST_VatThe instance);
    partial void UpdateST_VatThe(ST_VatThe instance);
    partial void DeleteST_VatThe(ST_VatThe instance);
    partial void InsertST_HoatDong(ST_HoatDong instance);
    partial void UpdateST_HoatDong(ST_HoatDong instance);
    partial void DeleteST_HoatDong(ST_HoatDong instance);
    partial void InsertST_User(ST_User instance);
    partial void UpdateST_User(ST_User instance);
    partial void DeleteST_User(ST_User instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::TestRada1.Properties.Settings.Default.DB_RadarConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ST_Department> ST_Departments
		{
			get
			{
				return this.GetTable<ST_Department>();
			}
		}
		
		public System.Data.Linq.Table<ST_VatThe> ST_VatThes
		{
			get
			{
				return this.GetTable<ST_VatThe>();
			}
		}
		
		public System.Data.Linq.Table<ST_HoatDong> ST_HoatDongs
		{
			get
			{
				return this.GetTable<ST_HoatDong>();
			}
		}
		
		public System.Data.Linq.Table<ST_User> ST_Users
		{
			get
			{
				return this.GetTable<ST_User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ST_Departments")]
	public partial class ST_Department : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _department_id;
		
		private string _department_name;
		
		private System.Nullable<long> _user_created;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondepartment_idChanging(long value);
    partial void Ondepartment_idChanged();
    partial void Ondepartment_nameChanging(string value);
    partial void Ondepartment_nameChanged();
    partial void Onuser_createdChanging(System.Nullable<long> value);
    partial void Onuser_createdChanged();
    #endregion
		
		public ST_Department()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long department_id
		{
			get
			{
				return this._department_id;
			}
			set
			{
				if ((this._department_id != value))
				{
					this.Ondepartment_idChanging(value);
					this.SendPropertyChanging();
					this._department_id = value;
					this.SendPropertyChanged("department_id");
					this.Ondepartment_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department_name", DbType="NVarChar(200)")]
		public string department_name
		{
			get
			{
				return this._department_name;
			}
			set
			{
				if ((this._department_name != value))
				{
					this.Ondepartment_nameChanging(value);
					this.SendPropertyChanging();
					this._department_name = value;
					this.SendPropertyChanged("department_name");
					this.Ondepartment_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_created", DbType="BigInt")]
		public System.Nullable<long> user_created
		{
			get
			{
				return this._user_created;
			}
			set
			{
				if ((this._user_created != value))
				{
					this.Onuser_createdChanging(value);
					this.SendPropertyChanging();
					this._user_created = value;
					this.SendPropertyChanged("user_created");
					this.Onuser_createdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ST_VatThe")]
	public partial class ST_VatThe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _vatThe_id;
		
		private string _vatThe_name;
		
		private System.Data.Linq.Binary _vatThe_hinhAnh;
		
		private string _vatThe_mau;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnvatThe_idChanging(int value);
    partial void OnvatThe_idChanged();
    partial void OnvatThe_nameChanging(string value);
    partial void OnvatThe_nameChanged();
    partial void OnvatThe_hinhAnhChanging(System.Data.Linq.Binary value);
    partial void OnvatThe_hinhAnhChanged();
    partial void OnvatThe_mauChanging(string value);
    partial void OnvatThe_mauChanged();
    #endregion
		
		public ST_VatThe()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vatThe_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int vatThe_id
		{
			get
			{
				return this._vatThe_id;
			}
			set
			{
				if ((this._vatThe_id != value))
				{
					this.OnvatThe_idChanging(value);
					this.SendPropertyChanging();
					this._vatThe_id = value;
					this.SendPropertyChanged("vatThe_id");
					this.OnvatThe_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vatThe_name", DbType="NVarChar(255)")]
		public string vatThe_name
		{
			get
			{
				return this._vatThe_name;
			}
			set
			{
				if ((this._vatThe_name != value))
				{
					this.OnvatThe_nameChanging(value);
					this.SendPropertyChanging();
					this._vatThe_name = value;
					this.SendPropertyChanged("vatThe_name");
					this.OnvatThe_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vatThe_hinhAnh", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary vatThe_hinhAnh
		{
			get
			{
				return this._vatThe_hinhAnh;
			}
			set
			{
				if ((this._vatThe_hinhAnh != value))
				{
					this.OnvatThe_hinhAnhChanging(value);
					this.SendPropertyChanging();
					this._vatThe_hinhAnh = value;
					this.SendPropertyChanged("vatThe_hinhAnh");
					this.OnvatThe_hinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vatThe_mau", DbType="VarChar(20)")]
		public string vatThe_mau
		{
			get
			{
				return this._vatThe_mau;
			}
			set
			{
				if ((this._vatThe_mau != value))
				{
					this.OnvatThe_mauChanging(value);
					this.SendPropertyChanging();
					this._vatThe_mau = value;
					this.SendPropertyChanged("vatThe_mau");
					this.OnvatThe_mauChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ST_HoatDong")]
	public partial class ST_HoatDong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _HoatDong_id;
		
		private System.Nullable<int> _vatThe_id;
		
		private System.Nullable<int> _HoatDong_xBatDau;
		
		private System.Nullable<int> _HoatDong_yBatDau;
		
		private System.Nullable<int> _HoatDong_xKetThuc;
		
		private System.Nullable<int> _HoatDong_yKetThuc;
		
		private System.Nullable<int> _HoatDong_soBuocNhay;
		
		private System.Nullable<System.DateTime> _HoatDong_thoiGianBatDauChay;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHoatDong_idChanging(int value);
    partial void OnHoatDong_idChanged();
    partial void OnvatThe_idChanging(System.Nullable<int> value);
    partial void OnvatThe_idChanged();
    partial void OnHoatDong_xBatDauChanging(System.Nullable<int> value);
    partial void OnHoatDong_xBatDauChanged();
    partial void OnHoatDong_yBatDauChanging(System.Nullable<int> value);
    partial void OnHoatDong_yBatDauChanged();
    partial void OnHoatDong_xKetThucChanging(System.Nullable<int> value);
    partial void OnHoatDong_xKetThucChanged();
    partial void OnHoatDong_yKetThucChanging(System.Nullable<int> value);
    partial void OnHoatDong_yKetThucChanged();
    partial void OnHoatDong_soBuocNhayChanging(System.Nullable<int> value);
    partial void OnHoatDong_soBuocNhayChanged();
    partial void OnHoatDong_thoiGianBatDauChayChanging(System.Nullable<System.DateTime> value);
    partial void OnHoatDong_thoiGianBatDauChayChanged();
    #endregion
		
		public ST_HoatDong()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoatDong_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int HoatDong_id
		{
			get
			{
				return this._HoatDong_id;
			}
			set
			{
				if ((this._HoatDong_id != value))
				{
					this.OnHoatDong_idChanging(value);
					this.SendPropertyChanging();
					this._HoatDong_id = value;
					this.SendPropertyChanged("HoatDong_id");
					this.OnHoatDong_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vatThe_id", DbType="Int")]
		public System.Nullable<int> vatThe_id
		{
			get
			{
				return this._vatThe_id;
			}
			set
			{
				if ((this._vatThe_id != value))
				{
					this.OnvatThe_idChanging(value);
					this.SendPropertyChanging();
					this._vatThe_id = value;
					this.SendPropertyChanged("vatThe_id");
					this.OnvatThe_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoatDong_xBatDau", DbType="Int")]
		public System.Nullable<int> HoatDong_xBatDau
		{
			get
			{
				return this._HoatDong_xBatDau;
			}
			set
			{
				if ((this._HoatDong_xBatDau != value))
				{
					this.OnHoatDong_xBatDauChanging(value);
					this.SendPropertyChanging();
					this._HoatDong_xBatDau = value;
					this.SendPropertyChanged("HoatDong_xBatDau");
					this.OnHoatDong_xBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoatDong_yBatDau", DbType="Int")]
		public System.Nullable<int> HoatDong_yBatDau
		{
			get
			{
				return this._HoatDong_yBatDau;
			}
			set
			{
				if ((this._HoatDong_yBatDau != value))
				{
					this.OnHoatDong_yBatDauChanging(value);
					this.SendPropertyChanging();
					this._HoatDong_yBatDau = value;
					this.SendPropertyChanged("HoatDong_yBatDau");
					this.OnHoatDong_yBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoatDong_xKetThuc", DbType="Int")]
		public System.Nullable<int> HoatDong_xKetThuc
		{
			get
			{
				return this._HoatDong_xKetThuc;
			}
			set
			{
				if ((this._HoatDong_xKetThuc != value))
				{
					this.OnHoatDong_xKetThucChanging(value);
					this.SendPropertyChanging();
					this._HoatDong_xKetThuc = value;
					this.SendPropertyChanged("HoatDong_xKetThuc");
					this.OnHoatDong_xKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoatDong_yKetThuc", DbType="Int")]
		public System.Nullable<int> HoatDong_yKetThuc
		{
			get
			{
				return this._HoatDong_yKetThuc;
			}
			set
			{
				if ((this._HoatDong_yKetThuc != value))
				{
					this.OnHoatDong_yKetThucChanging(value);
					this.SendPropertyChanging();
					this._HoatDong_yKetThuc = value;
					this.SendPropertyChanged("HoatDong_yKetThuc");
					this.OnHoatDong_yKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoatDong_soBuocNhay", DbType="Int")]
		public System.Nullable<int> HoatDong_soBuocNhay
		{
			get
			{
				return this._HoatDong_soBuocNhay;
			}
			set
			{
				if ((this._HoatDong_soBuocNhay != value))
				{
					this.OnHoatDong_soBuocNhayChanging(value);
					this.SendPropertyChanging();
					this._HoatDong_soBuocNhay = value;
					this.SendPropertyChanged("HoatDong_soBuocNhay");
					this.OnHoatDong_soBuocNhayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoatDong_thoiGianBatDauChay", DbType="DateTime")]
		public System.Nullable<System.DateTime> HoatDong_thoiGianBatDauChay
		{
			get
			{
				return this._HoatDong_thoiGianBatDauChay;
			}
			set
			{
				if ((this._HoatDong_thoiGianBatDauChay != value))
				{
					this.OnHoatDong_thoiGianBatDauChayChanging(value);
					this.SendPropertyChanging();
					this._HoatDong_thoiGianBatDauChay = value;
					this.SendPropertyChanged("HoatDong_thoiGianBatDauChay");
					this.OnHoatDong_thoiGianBatDauChayChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ST_Users")]
	public partial class ST_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _user_id;
		
		private string _user_name;
		
		private string _user_username;
		
		private string _user_password;
		
		private string _user_address;
		
		private string _user_email;
		
		private string _user_phone;
		
		private System.Nullable<System.DateTime> _user_date_of_birth;
		
		private System.Nullable<bool> _user_gender;
		
		private System.Data.Linq.Binary _user_image;
		
		private System.Nullable<long> _role_id;
		
		private System.Nullable<long> _department_id;
		
		private System.Nullable<bool> _user_status;
		
		private System.Nullable<System.DateTime> _user_created_date;
		
		private System.Nullable<long> _user_created;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(long value);
    partial void Onuser_idChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void Onuser_usernameChanging(string value);
    partial void Onuser_usernameChanged();
    partial void Onuser_passwordChanging(string value);
    partial void Onuser_passwordChanged();
    partial void Onuser_addressChanging(string value);
    partial void Onuser_addressChanged();
    partial void Onuser_emailChanging(string value);
    partial void Onuser_emailChanged();
    partial void Onuser_phoneChanging(string value);
    partial void Onuser_phoneChanged();
    partial void Onuser_date_of_birthChanging(System.Nullable<System.DateTime> value);
    partial void Onuser_date_of_birthChanged();
    partial void Onuser_genderChanging(System.Nullable<bool> value);
    partial void Onuser_genderChanged();
    partial void Onuser_imageChanging(System.Data.Linq.Binary value);
    partial void Onuser_imageChanged();
    partial void Onrole_idChanging(System.Nullable<long> value);
    partial void Onrole_idChanged();
    partial void Ondepartment_idChanging(System.Nullable<long> value);
    partial void Ondepartment_idChanged();
    partial void Onuser_statusChanging(System.Nullable<bool> value);
    partial void Onuser_statusChanged();
    partial void Onuser_created_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onuser_created_dateChanged();
    partial void Onuser_createdChanging(System.Nullable<long> value);
    partial void Onuser_createdChanged();
    #endregion
		
		public ST_User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="NVarChar(200)")]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_username", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string user_username
		{
			get
			{
				return this._user_username;
			}
			set
			{
				if ((this._user_username != value))
				{
					this.Onuser_usernameChanging(value);
					this.SendPropertyChanging();
					this._user_username = value;
					this.SendPropertyChanged("user_username");
					this.Onuser_usernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_password", DbType="VarChar(255)")]
		public string user_password
		{
			get
			{
				return this._user_password;
			}
			set
			{
				if ((this._user_password != value))
				{
					this.Onuser_passwordChanging(value);
					this.SendPropertyChanging();
					this._user_password = value;
					this.SendPropertyChanged("user_password");
					this.Onuser_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_address", DbType="NVarChar(255)")]
		public string user_address
		{
			get
			{
				return this._user_address;
			}
			set
			{
				if ((this._user_address != value))
				{
					this.Onuser_addressChanging(value);
					this.SendPropertyChanging();
					this._user_address = value;
					this.SendPropertyChanged("user_address");
					this.Onuser_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_email", DbType="VarChar(50)")]
		public string user_email
		{
			get
			{
				return this._user_email;
			}
			set
			{
				if ((this._user_email != value))
				{
					this.Onuser_emailChanging(value);
					this.SendPropertyChanging();
					this._user_email = value;
					this.SendPropertyChanged("user_email");
					this.Onuser_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_phone", DbType="NVarChar(50)")]
		public string user_phone
		{
			get
			{
				return this._user_phone;
			}
			set
			{
				if ((this._user_phone != value))
				{
					this.Onuser_phoneChanging(value);
					this.SendPropertyChanging();
					this._user_phone = value;
					this.SendPropertyChanged("user_phone");
					this.Onuser_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_date_of_birth", DbType="DateTime")]
		public System.Nullable<System.DateTime> user_date_of_birth
		{
			get
			{
				return this._user_date_of_birth;
			}
			set
			{
				if ((this._user_date_of_birth != value))
				{
					this.Onuser_date_of_birthChanging(value);
					this.SendPropertyChanging();
					this._user_date_of_birth = value;
					this.SendPropertyChanged("user_date_of_birth");
					this.Onuser_date_of_birthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_gender", DbType="Bit")]
		public System.Nullable<bool> user_gender
		{
			get
			{
				return this._user_gender;
			}
			set
			{
				if ((this._user_gender != value))
				{
					this.Onuser_genderChanging(value);
					this.SendPropertyChanging();
					this._user_gender = value;
					this.SendPropertyChanged("user_gender");
					this.Onuser_genderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_image", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary user_image
		{
			get
			{
				return this._user_image;
			}
			set
			{
				if ((this._user_image != value))
				{
					this.Onuser_imageChanging(value);
					this.SendPropertyChanging();
					this._user_image = value;
					this.SendPropertyChanged("user_image");
					this.Onuser_imageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role_id", DbType="BigInt")]
		public System.Nullable<long> role_id
		{
			get
			{
				return this._role_id;
			}
			set
			{
				if ((this._role_id != value))
				{
					this.Onrole_idChanging(value);
					this.SendPropertyChanging();
					this._role_id = value;
					this.SendPropertyChanged("role_id");
					this.Onrole_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department_id", DbType="BigInt")]
		public System.Nullable<long> department_id
		{
			get
			{
				return this._department_id;
			}
			set
			{
				if ((this._department_id != value))
				{
					this.Ondepartment_idChanging(value);
					this.SendPropertyChanging();
					this._department_id = value;
					this.SendPropertyChanged("department_id");
					this.Ondepartment_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_status", DbType="Bit")]
		public System.Nullable<bool> user_status
		{
			get
			{
				return this._user_status;
			}
			set
			{
				if ((this._user_status != value))
				{
					this.Onuser_statusChanging(value);
					this.SendPropertyChanging();
					this._user_status = value;
					this.SendPropertyChanged("user_status");
					this.Onuser_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_created_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> user_created_date
		{
			get
			{
				return this._user_created_date;
			}
			set
			{
				if ((this._user_created_date != value))
				{
					this.Onuser_created_dateChanging(value);
					this.SendPropertyChanging();
					this._user_created_date = value;
					this.SendPropertyChanged("user_created_date");
					this.Onuser_created_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_created", DbType="BigInt")]
		public System.Nullable<long> user_created
		{
			get
			{
				return this._user_created;
			}
			set
			{
				if ((this._user_created != value))
				{
					this.Onuser_createdChanging(value);
					this.SendPropertyChanging();
					this._user_created = value;
					this.SendPropertyChanged("user_created");
					this.Onuser_createdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
